apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: demo-10-11
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/jberger-tenant/demo-10-11/demo-10-11@sha256:0c66685ac1e57c40f18841a3854d5d418bdb5566adcaaa1e26f9ae235f2aa22c
        name: my-java-springboot
        resources: {}
status: {}
